data <- read.table("./household_power_consumption.txt", header = TRUE, nrows=70000, sep=";", na.strings="?", colClasses=c("character","character", rep("numeric",7)))
data$Date <- paste(data$Date, data$Time,sep = " ")
data$Date <- strptime(data$Date, format="%d/%m/%Y %H:%M:%OS")
start <- strptime("2007-02-01 00:00:00", format="%Y-%m-%d  %H:%M:%OS")
end <- strptime("2007-02-03 00:00:00", format="%Y-%m-%d  %H:%M:%OS")
filter <- which(data$Date >= start & data$Date < end)
data <- data[filter,]
png(filename = "plot3.png", width=480, height=480, units="px")
plot(range(data$Date), range(c(data$Sub_metering_1, data$Sub_metering_2, data$Sub_metering_3)), type='n',ylab="Energy sub metering" , xlab='')
lines(data$Date, data$Sub_metering_1, type='l', col='black')
lines(data$Date, data$Sub_metering_2, type='l', col='red')
lines(data$Date, data$Sub_metering_3, type='l', col='blue')
legend("topright", lty=1, col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()