data <- read.table("./household_power_consumption.txt", header = TRUE, nrows=70000, sep=";", na.strings="?", colClasses=c("character","character", rep("numeric",7)))
data$Date <- paste(data$Date, data$Time,sep = " ")
data$Date <- strptime(data$Date, format="%d/%m/%Y %H:%M:%OS")
start <- strptime("2007-02-01 00:00:00", format="%Y-%m-%d  %H:%M:%OS")
end <- strptime("2007-02-03 00:00:00", format="%Y-%m-%d  %H:%M:%OS")
filter <- which(data$Date >= start & data$Date < end)
data <- data[filter,]
png(filename = "plot2.png", width=480, height=480, units="px")
plot(data$Date, data$Global_active_power, type='l', ylab="Global Active Power (kilowatts)", xlab='')
dev.off()